### ISSUE TITLE
Error trying to run python active_inference_basic.py --mode m1_goal_error_nd

### ISSUE THREAD

**Issue by noob-ja** [x75/actinf#1]
```
Traceback (most recent call last):
  File "active_inference_basic.py", line 12, in <module>
    import explauto
  File "/home/jiaaun/anaconda3/lib/python3.6/site-packages/explauto-1.3.0-py3.6.egg/explauto/__init__.py", line 7, in <module>
  File "/home/jiaaun/anaconda3/lib/python3.6/site-packages/explauto-1.3.0-py3.6.egg/explauto/sensorimotor_model/__init__.py", line 7, in <module>
  File "/home/jiaaun/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/jiaaun/anaconda3/lib/python3.6/site-packages/explauto-1.3.0-py3.6.egg/explauto/sensorimotor_model/force.py", line 10, in <module>
ModuleNotFoundError: No module named 'imol'
```

i installed all the dependencies as required
running on 
python 3.6.8 :: Anaconda, Inc.
ubuntu 18.04 LTS

looking at the code in force.py
```
sys.path.insert(0, "/home/src/QK/smp/imol")

from imol.models import LinearNetwork, ReservoirNetwork
```
it appears that im missing the files
where can i get them please?
thanks

**Comment by x75** [comment]
hi noob-ja, thanks for posting that.

i did a bit of clean up in actinf, explauto and sliced out the imol submodule from the smp project on
 
https://github.com/x75/imol

Quickest way forward probably is to just copy that somewhere into your PYTHONPATH and change the import line in force.py

Otherwise, you'd need to clone imol repo and also smp_base repo and add this dirs to PYTHONPATH.

Either way, if that fixes it for you, there will certainly be some more issues down the road. It's all work-in-progress, your feedback is valuable to improve it.

bst, opt

**Comment by noob-ja** [comment]
thanks for the prompt reply
thanks for the guides to run it 

i encounter a different error this time.
```
Traceback (most recent call last):
  File "active_inference_basic.py", line 1789, in <module>
    main(args)
  File "active_inference_basic.py", line 1772, in main
    inf.run()
  File "active_inference_basic.py", line 977, in run
    v()
  File "active_inference_basic.py", line 534, in rh_check_for_model_and_map
    self.map_model_m1_goal_error_nd()
  File "active_inference_basic.py", line 1324, in map_model_m1_goal_error_nd
    from smp.dimstack import dimensional_stacking
ModuleNotFoundError: No module named 'smp'
```

looking into the code, just need to change from original
```
from smp.dimstack import dimensional_stacking
from smp.smp_plot import resize_panel_vert, resize_panel_horiz, put_legend_out_right, put_legend_out_top
```
to this
```
from smp_base.dimstack import dimensional_stacking
from smp_base.plot_utils import resize_panel_vert, resize_panel_horiz, put_legend_out_right, put_legend_out_top
```

**Comment by x75** [comment]
yup, see above. thanks. let me know whatever breaks next ;)

**Comment by noob-ja** [comment]
working so far so good
thx for the help :+1:
